"""
VoxelMask Research Mode De-identification Tests
================================================
Verifies that US Research (HIPAA Safe Harbor) mode correctly:
1. REMOVES or anonymizes PatientName
2. Does NOT equal the original PatientName in the output (should be "Anonymous" or removed)
3. Preserves study integrity while removing identifiable information

Run with: pytest tests/test_research_mode.py -v
"""

import pytest
import pydicom


# Import the compliance engine from src
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from compliance_engine import DicomComplianceManager


class TestUSResearchMode:
    """Test suite for US Research (HIPAA Safe Harbor) de-identification profile."""
    
    def test_patient_name_anonymized(self, dummy_dicom_file):
        """
        Assert: PatientName is removed or equals "Anonymous".
        
        Per HIPAA Safe Harbor, patient names must be removed or replaced
        with a non-identifying placeholder.
        """
        # Load the original DICOM
        original_ds = pydicom.dcmread(dummy_dicom_file)
        original_patient_name = str(original_ds.PatientName)
        
        # Verify our test file has a real patient name
        assert original_patient_name == "Test^Patient", \
            f"Test fixture should have 'Test^Patient', got '{original_patient_name}'"
        
        # Process with US Research profile
        manager = DicomComplianceManager()
        processed_ds, info = manager.process_dataset(
            original_ds.copy(),
            DicomComplianceManager.PROFILE_US_RESEARCH
        )
        
        # Check: PatientName should be removed or anonymous
        if hasattr(processed_ds, 'PatientName'):
            processed_name = str(processed_ds.PatientName)
            # Name should either be empty, "Anonymous", or some anonymized value
            assert processed_name != original_patient_name, \
                f"PatientName should not equal original '{original_patient_name}'"
            # If present, should be anonymous-style
            assert processed_name in ['', 'Anonymous', 'ANONYMOUS'] or \
                   processed_name.startswith('ANON'), \
                f"If PatientName exists, should be anonymous-style, got '{processed_name}'"
        # If attribute doesn't exist, that's also valid (removed)
        
        # Verify profile was applied correctly
        assert info['profile'] == 'us_research_safe_harbor'
    
    def test_study_date_shifted_in_us_research(self, dummy_dicom_file):
        """
        Assert: StudyDate is SHIFTED (not equal to original) in US Research mode.
        
        Per HIPAA Safe Harbor best practices, dates should be shifted by a 
        random offset to prevent re-identification while maintaining temporal
        relationships within a patient's records.
        """
        # Load the original DICOM
        original_ds = pydicom.dcmread(dummy_dicom_file)
        original_study_date = str(original_ds.StudyDate)
        
        # Verify our test file has a study date
        assert original_study_date == "20231201", \
            f"Test fixture should have StudyDate '20231201', got '{original_study_date}'"
        
        # Process with US Research profile
        manager = DicomComplianceManager()
        processed_ds, info = manager.process_dataset(
            original_ds.copy(),
            DicomComplianceManager.PROFILE_US_RESEARCH
        )
        
        # StudyDate should be SHIFTED in US Research mode
        processed_date = str(processed_ds.StudyDate)
        assert processed_date != original_study_date, \
            f"US Research should SHIFT StudyDate, got '{processed_date}' == '{original_study_date}'"
        
        # Verify the shift is recorded in processing info
        assert info['date_shift_days'] is not None, \
            "date_shift_days should be recorded in processing info"
        assert info['date_shift_days'] < 0, \
            "date_shift_days should be negative (dates shifted to past)"

    
    def test_study_instance_uid_regenerated_in_us_research(self, dummy_dicom_file):
        """
        Assert: StudyInstanceUID is regenerated in US Research mode.
        
        UIDs are now regenerated by default in US Research to prevent 
        re-identification through UID correlation.
        """
        # Load the original DICOM
        original_ds = pydicom.dcmread(dummy_dicom_file)
        original_study_uid = str(original_ds.StudyInstanceUID)
        
        # Process with US Research profile
        manager = DicomComplianceManager()
        processed_ds, info = manager.process_dataset(
            original_ds.copy(),
            DicomComplianceManager.PROFILE_US_RESEARCH
        )
        
        # UID should be regenerated by default in US Research mode
        processed_uid = str(processed_ds.StudyInstanceUID)
        assert processed_uid != original_study_uid, \
            f"StudyInstanceUID should be regenerated in US Research mode"
        
        # Verify UID mapping info is present
        assert info['uid_mapping'] is not None
        assert info['uid_mapping']['studies_remapped'] >= 1
    
    def test_uid_regeneration_is_deterministic(self, dummy_dicom_file):
        """
        Assert: UID regeneration produces new UIDs (different from original).
        
        The UID manager generates new UIDs for each processing run to ensure
        de-identification. This test verifies UIDs are actually changed.
        """
        # Load the original DICOM and capture original UID as string
        original_ds = pydicom.dcmread(dummy_dicom_file)
        original_study_uid = str(original_ds.StudyInstanceUID)  # Capture before processing
        
        # Process with US Research profile
        manager1 = DicomComplianceManager()
        processed_ds1, info1 = manager1.process_dataset(
            original_ds.copy(),
            DicomComplianceManager.PROFILE_US_RESEARCH
        )
        
        # Get processed UID
        uid1 = str(processed_ds1.StudyInstanceUID)
        
        # UIDs should be different from original
        assert uid1 != original_study_uid, \
            f"Processed UID should differ from original: {uid1} vs {original_study_uid}"
        
        # Verify UID regeneration was recorded
        assert info1['uid_mapping'] is not None
        assert info1['uid_mapping']['studies_remapped'] >= 1

    
    def test_patient_identity_removed_flag_set(self, dummy_dicom_file):
        """
        Assert: PatientIdentityRemoved is set to 'YES' after processing.
        
        DICOM compliance requires this flag to indicate de-identification.
        """
        # Load and process
        original_ds = pydicom.dcmread(dummy_dicom_file)
        
        manager = DicomComplianceManager()
        processed_ds, info = manager.process_dataset(
            original_ds.copy(),
            DicomComplianceManager.PROFILE_US_RESEARCH
        )
        
        # Check compliance flag
        assert hasattr(processed_ds, 'PatientIdentityRemoved'), \
            "PatientIdentityRemoved attribute should exist"
        assert str(processed_ds.PatientIdentityRemoved) == 'YES', \
            "PatientIdentityRemoved should be 'YES'"
    
    def test_deidentification_method_recorded(self, dummy_dicom_file):
        """
        Assert: DeidentificationMethod contains HIPAA indicator.
        
        The de-identification method should be recorded for audit purposes.
        """
        # Load and process
        original_ds = pydicom.dcmread(dummy_dicom_file)
        
        manager = DicomComplianceManager()
        processed_ds, info = manager.process_dataset(
            original_ds.copy(),
            DicomComplianceManager.PROFILE_US_RESEARCH
        )
        
        # Check method is recorded
        assert hasattr(processed_ds, 'DeidentificationMethod'), \
            "DeidentificationMethod attribute should exist"
        
        method = str(processed_ds.DeidentificationMethod)
        assert 'HIPAA' in method or 'SAFE_HARBOR' in method or 'VOXELMASK' in method, \
            f"DeidentificationMethod should reference HIPAA/Safe Harbor, got '{method}'"
    
    def test_private_tags_removed(self, dummy_dicom_file):
        """
        Assert: Private tags are removed in US Research mode.
        
        Private tags may contain PHI and should be stripped.
        """
        # Load the original DICOM and add a private tag
        original_ds = pydicom.dcmread(dummy_dicom_file)
        
        # Add a private tag (group 0x0011 with element 0x0010)
        original_ds.add_new(0x00110010, 'LO', 'Private Creator')
        original_ds.add_new(0x00111001, 'LO', 'SensitivePrivateData')
        
        # Verify private tag exists
        private_tags_before = [elem for elem in original_ds if elem.tag.is_private]
        assert len(private_tags_before) > 0, "Test should add private tags"
        
        # Process with US Research profile
        manager = DicomComplianceManager()
        processed_ds, info = manager.process_dataset(
            original_ds.copy(),
            DicomComplianceManager.PROFILE_US_RESEARCH
        )
        
        # Check private tags are removed
        private_tags_after = [elem for elem in processed_ds if elem.tag.is_private]
        assert len(private_tags_after) == 0, \
            f"Private tags should be removed, found {len(private_tags_after)}"
